<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5757b93da8d5c',
    'title' => 'Contacts',
    'fields' => array(
        0 => array(
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array(
                'cards' => __('Cards', 'modularity'),
                'list' => __('List', 'modularity'),
            ),
            'default_value' => array(
                0 => 'cards',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_5757c8f61a2a3',
            'label' => __('Display mode', 'modularity'),
            'name' => 'display_mode',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'disabled' => 0,
            'readonly' => 0,
        ),
        1 => array(
            'layouts' => array(
                0 => array(
                    'key' => '5757b95767730',
                    'name' => 'custom',
                    'label' => 'Custom',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                            'key' => 'field_5757b9a5fecc8',
                            'label' => __('Image', 'modularity'),
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        1 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5757b9b1fecc9',
                            'label' => __('First name or place', 'modularity'),
                            'name' => 'first_name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        2 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5757b9befecca',
                            'label' => __('Last name', 'modularity'),
                            'name' => 'last_name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '50',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        3 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5757b9cdfeccb',
                            'label' => __('Work title', 'modularity'),
                            'name' => 'work_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        4 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5757b9e8feccc',
                            'label' => __('Administration unit', 'modularity'),
                            'name' => 'administration_unit',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        5 => array(
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5757ba00feccd',
                            'label' => __('Epost', 'modularity'),
                            'name' => 'email',
                            'type' => 'email',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        6 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_5757ba20fecce',
                            'label' => __('Phone', 'modularity'),
                            'name' => 'phone',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        7 => array(
                            'default_value' => '',
                            'new_lines' => 'wpautop',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => '',
                            'key' => 'field_5757ba40feccf',
                            'label' => __('Adress', 'modularity'),
                            'name' => 'address',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        8 => array(
                            'default_value' => '',
                            'new_lines' => 'wpautop',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => '',
                            'key' => 'field_5757ba5ffecd0',
                            'label' => __('Visiting address', 'modularity'),
                            'name' => 'visiting_address',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        9 => array(
                            'default_value' => '',
                            'new_lines' => 'wpautop',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => '',
                            'key' => 'field_5757ba74fecd1',
                            'label' => __('Opening hours', 'modularity'),
                            'name' => 'opening_hours',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        10 => array(
                            'tabs' => 'all',
                            'toolbar' => 'full',
                            'media_upload' => 1,
                            'default_value' => '',
                            'delay' => 0,
                            'key' => 'field_57a06dd3a9c48',
                            'label' => __('Other', 'modularity'),
                            'name' => 'other',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                1 => array(
                    'key' => '5757b97ffecc6',
                    'name' => 'user',
                    'label' => 'User',
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'role' => '',
                            'multiple' => 0,
                            'allow_null' => 0,
                            'key' => 'field_5757b986fecc7',
                            'label' => __('Select user', 'modularity'),
                            'name' => 'user',
                            'type' => 'user',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'min' => 1,
            'max' => '',
            'button_label' => 'Add contact',
            'key' => 'field_5757b947fecc5',
            'label' => __('Kontakter', 'modularity'),
            'name' => 'contacts',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array(
                'grid-md-12' => __('1', 'modularity'),
                'grid-md-6' => __('2', 'modularity'),
                'grid-md-4' => __('3', 'modularity'),
                'grid-md-3' => __('4', 'modularity'),
            ),
            'default_value' => array(
                0 => 'grid-md-12',
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_577e3e2d3e1e4',
            'label' => __('Columns', 'modularity'),
            'name' => 'columns',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5757c8f61a2a3',
                        'operator' => '==',
                        'value' => 'cards',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'disabled' => 0,
            'readonly' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-contact',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'modified' => 1474621898,
    'local' => 'json',
));
}