<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_570770ab8f064',
    'title' => 'Image',
    'fields' => array(
        0 => array(
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => 'jpg, png, gif',
            'key' => 'field_570770b8e2e61',
            'label' => __('Image', 'modularity'),
            'name' => 'mod_image_image',
            'type' => 'image',
            'instructions' => __('Allowed file types: jpg, png, gif', 'modularity'),
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'default_value' => '',
            'new_lines' => 'br',
            'maxlength' => '',
            'placeholder' => '',
            'rows' => 4,
            'key' => 'field_587604df2975f',
            'label' => __('Image caption', 'modularity'),
            'name' => 'mod_image_caption',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'default_value' => 1,
            'message' => __('Crop image', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_570770f5e2e62',
            'label' => __('Cropping', 'modularity'),
            'name' => 'mod_image_crop',
            'type' => 'true_false',
            'instructions' => __('Check if you wold like to crop your image to a specific size', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
        ),
        3 => array(
            'default_value' => 1,
            'message' => __('Yes, make this image responsive', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_570775955b8de',
            'label' => __('Responsive', 'modularity'),
            'name' => 'mod_image_responsive',
            'type' => 'true_false',
            'instructions' => __('Make the image responsive if you would like it to automatically resize to fit inside its container.', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
        ),
        4 => array(
            'default_value' => '',
            'min' => 1,
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('pixels', 'modularity'),
            'key' => 'field_57077112e2e63',
            'label' => __('Crop width', 'modularity'),
            'name' => 'mod_image_crop_width',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_570770f5e2e62',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        5 => array(
            'default_value' => '',
            'min' => 1,
            'max' => '',
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => __('pixels', 'modularity'),
            'key' => 'field_5707712be2e64',
            'label' => __('Crop height', 'modularity'),
            'name' => 'mod_image_crop_height',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_570770f5e2e62',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        6 => array(
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array(
                'thumbnail' => 'thumbnail',
                'medium' => 'medium',
                'medium_large' => 'medium_large',
                'large' => 'large',
            ),
            'default_value' => array(
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
            'key' => 'field_5707716fabf17',
            'label' => __('Image size', 'modularity'),
            'name' => 'mod_image_size',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_570770f5e2e62',
                        'operator' => '!=',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'disabled' => 0,
            'readonly' => 0,
        ),
        7 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'false' => __('None', 'modularity'),
                'internal' => __('Internal', 'modularity'),
                'external' => __('External', 'modularity'),
            ),
            'default_value' => '',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_577d07c8d72db',
            'label' => __('Link', 'modularity'),
            'name' => 'mod_image_link',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        8 => array(
            'default_value' => '',
            'placeholder' => '',
            'key' => 'field_577d0810d72dc',
            'label' => __('Link url', 'modularity'),
            'name' => 'mod_image_link_url',
            'type' => 'url',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_577d07c8d72db',
                        'operator' => '==',
                        'value' => 'external',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        9 => array(
            'post_type' => array(
            ),
            'taxonomy' => array(
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'allow_archives' => 1,
            'key' => 'field_577d0840d72dd',
            'label' => __('Link page', 'modularity'),
            'name' => 'mod_image_link_url',
            'type' => 'page_link',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_577d07c8d72db',
                        'operator' => '==',
                        'value' => 'internal',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-image',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'modified' => 1484129869,
    'local' => 'json',
));
}