<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_5666a2a71d806',
    'title' => 'Table Editor',
    'fields' => array(
        0 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'manual' => __('Manual input', 'modularity'),
                'csv' => __('CSV Import', 'modularity'),
            ),
            'default_value' => '',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_5731982808842',
            'label' => __('Data type', 'modularity'),
            'name' => 'mod_table_data_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '.csv',
            'key' => 'field_57319c3b08843',
            'label' => __('CSV File', 'modularity'),
            'name' => 'mod_table_csv_file',
            'type' => 'file',
            'instructions' => __('CSV formatted file', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731982808842',
                        'operator' => '==',
                        'value' => 'csv',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'default_value' => ';',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5731a138b52aa',
            'label' => __('CSV Delimiter', 'modularity'),
            'name' => 'mod_table_csv_delimiter',
            'type' => 'text',
            'instructions' => __('CSV Delimiter character. Usually comma or semicolon.', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731982808842',
                        'operator' => '==',
                        'value' => 'csv',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        3 => array(
            'key' => 'field_5666a2ae23643',
            'label' => __('Table', 'modularity'),
            'name' => 'mod_table',
            'type' => 'dynamic_table',
            'instructions' => __('Enter your table contents, and select appearance and functionality options below.', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731982808842',
                        'operator' => '==',
                        'value' => 'manual',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'tableclass' => 'modularity-table',
            'maxrows' => '',
            'disable_sort' => 0,
            'fixed_columns' => 0,
            'default_headers' => '',
            'default_header' => '',
            'readonly' => 0,
            'disabled' => 0,
            'sub_fields' => false,
        ),
        4 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'table-striped' => __('Striped rows', 'modularity'),
                'table-bordered' => __('Bordered rows', 'modularity'),
                'table-hover' => __('Mouseover indication on rows', 'modularity'),
            ),
            'default_value' => array(
            ),
            'allow_custom' => 0,
            'save_custom' => 0,
            'toggle' => 0,
            'return_format' => 'value',
            'key' => 'field_56d97e463bf53',
            'label' => __('Display options', 'modularity'),
            'name' => 'mod_table_classes',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
        ),
        5 => array(
            'layout' => 'horizontal',
            'choices' => array(
                'table-sm' => __('Small', 'modularity'),
                'table-md' => __('Medium (default)', 'modularity'),
                'table-lg' => __('Large', 'modularity'),
            ),
            'default_value' => 'table-md',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
            'key' => 'field_57e8db8cf1ece',
            'label' => __('Size', 'modularity'),
            'name' => 'mod_table_size',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
        ),
        6 => array(
            'default_value' => 1,
            'message' => __('Yes, use pagination on this table', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_5666a3e0d2d29',
            'label' => __('Enable pagination', 'modularity'),
            'name' => 'mod_table_pagination',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
        ),
        7 => array(
            'default_value' => 10,
            'min' => 1,
            'max' => 500,
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'key' => 'field_5666a59673385',
            'label' => __('Number of posts/page', 'modularity'),
            'name' => 'mod_table_pagination_count',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5666a3e0d2d29',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'readonly' => 0,
            'disabled' => 0,
        ),
        8 => array(
            'default_value' => 1,
            'message' => __('Yes, use search on this table', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_5666a459d2d2a',
            'label' => __('Enable search', 'modularity'),
            'name' => 'mod_table_search',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
        ),
        9 => array(
            'default_value' => 1,
            'message' => __('Yes, enable column sorting', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_56e181adef7ac',
            'label' => __('Enable column soring', 'modularity'),
            'name' => 'mod_table_ordering',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-table',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'modified' => 1474878447,
    'local' => 'json',
));

}
