<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_57454ae7b0e9a',
    'title' => __('Video', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_57454c24d44d8',
            'label' => __('Type', 'modularity'),
            'name' => 'type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'embed' => __('Embed by link (YouTube or Vimeo)', 'modularity'),
                'upload' => __('Upload video file', 'modularity'),
            ),
            'default_value' => '',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        1 => array(
            'key' => 'field_57454c5ad44db',
            'label' => __('Video: mp4', 'modularity'),
            'name' => 'video_mp4',
            'type' => 'file',
            'instructions' => __('Upload or select file from library. The only valid file format is .mp4', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_57454c24d44d8',
                        'operator' => '==',
                        'value' => 'upload',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '33.3333',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => 'mp4',
        ),
        2 => array(
            'key' => 'field_57454c7ad44dc',
            'label' => __('Embed Link', 'modularity'),
            'name' => 'embed_link',
            'type' => 'url',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_57454c24d44d8',
                        'operator' => '==',
                        'value' => 'embed',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
        ),
        3 => array(
            'key' => 'field_57454c91d44dd',
            'label' => __('Placeholder Image', 'modularity'),
            'name' => 'placeholder_image',
            'type' => 'image',
            'instructions' => __('The placeholder image is displayed before the video is played. If an embed link has been used to embed this video, a placeholder will automatically be feted from embedded service. You can still use this field, to replace the image shown.', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'uploader' => '',
            'acfe_thumbnail' => 0,
            'return_format' => 'array',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        4 => array(
            'key' => 'field_637f27e8eb86c',
            'label' => __('Subtitles', 'modularity'),
            'name' => 'subtitles',
            'type' => 'repeater',
            'instructions' => __('Subtitles is required to be formatted as VTT files in order to work with all browsers.', 'modularity'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_57454c24d44d8',
                        'operator' => '==',
                        'value' => 'upload',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 1,
            'layout' => 'table',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Add Row', 'modularity'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_637f2831eb86d',
                    'label' => __('Subtitle File', 'modularity'),
                    'name' => 'file',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'uploader' => '',
                    'return_format' => 'url',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => 'vtt',
                    'library' => 'all',
                    'parent_repeater' => 'field_637f27e8eb86c',
                ),
                1 => array(
                    'key' => 'field_637f2869eb86e',
                    'label' => __('Language', 'modularity'),
                    'name' => 'language',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'ab' => __('Abkhaz', 'modularity'),
                        'aa' => __('Afar', 'modularity'),
                        'af' => __('Afrikaans', 'modularity'),
                        'ak' => __('Akan', 'modularity'),
                        'sq' => __('Albanian', 'modularity'),
                        'am' => __('Amharic', 'modularity'),
                        'ar' => __('Arabic', 'modularity'),
                        'an' => __('Aragonese', 'modularity'),
                        'hy' => __('Armenian', 'modularity'),
                        'as' => __('Assamese', 'modularity'),
                        'av' => __('Avaric', 'modularity'),
                        'az' => __('Azerbaijani', 'modularity'),
                        'bm' => __('Bambara', 'modularity'),
                        'ba' => __('Bashkir', 'modularity'),
                        'eu' => __('Basque', 'modularity'),
                        'be' => __('Belarusian', 'modularity'),
                        'bn' => __('Bengali', 'modularity'),
                        'bh' => __('Bihari', 'modularity'),
                        'bi' => __('Bislama', 'modularity'),
                        'bs' => __('Bosnian', 'modularity'),
                        'br' => __('Breton', 'modularity'),
                        'bg' => __('Bulgarian', 'modularity'),
                        'my' => __('Burmese', 'modularity'),
                        'ca' => __('Catalan; Valencian', 'modularity'),
                        'ch' => __('Chamorro', 'modularity'),
                        'ce' => __('Chechen', 'modularity'),
                        'ny' => __('Chichewa; Chewa; Nyanja', 'modularity'),
                        'zh' => __('Chinese', 'modularity'),
                        'cv' => __('Chuvash', 'modularity'),
                        'kw' => __('Cornish', 'modularity'),
                        'co' => __('Corsican', 'modularity'),
                        'cr' => __('Cree', 'modularity'),
                        'hr' => __('Croatian', 'modularity'),
                        'cs' => __('Czech', 'modularity'),
                        'da' => __('Danish', 'modularity'),
                        'dv' => __('Divehi', 'modularity'),
                        'nl' => __('Dutch', 'modularity'),
                        'en' => __('English', 'modularity'),
                        'eo' => __('Esperanto', 'modularity'),
                        'et' => __('Estonian', 'modularity'),
                        'ee' => __('Ewe', 'modularity'),
                        'fo' => __('Faroese', 'modularity'),
                        'fj' => __('Fijian', 'modularity'),
                        'fi' => __('Finnish', 'modularity'),
                        'fr' => __('French', 'modularity'),
                        'ff' => __('Fula', 'modularity'),
                        'gl' => __('Galician', 'modularity'),
                        'ka' => __('Georgian', 'modularity'),
                        'de' => __('German', 'modularity'),
                        'el' => __('Greek', 'modularity'),
                        'gn' => __('Guaraní', 'modularity'),
                        'gu' => __('Gujarat', 'modularity'),
                        'ht' => __('Haitian', 'modularity'),
                        'ha' => __('Hausa', 'modularity'),
                        'he' => __('Hebrew', 'modularity'),
                        'hz' => __('Herero', 'modularity'),
                        'hi' => __('Hindi', 'modularity'),
                        'ho' => __('Hiri Motu', 'modularity'),
                        'hu' => __('Hungarian', 'modularity'),
                        'ia' => __('Interlingua', 'modularity'),
                        'id' => __('Indonesian', 'modularity'),
                        'ie' => __('Interlingue', 'modularity'),
                        'ga' => __('Irish', 'modularity'),
                        'ig' => __('Igbo', 'modularity'),
                        'ik' => __('Inupiaq', 'modularity'),
                        'io' => __('Ido', 'modularity'),
                        'is' => __('Icelandic', 'modularity'),
                        'it' => __('Italian', 'modularity'),
                        'iu' => __('Inuktitut', 'modularity'),
                        'ja' => __('Japanese', 'modularity'),
                        'jv' => __('Javanese', 'modularity'),
                        'kl' => __('Kalaallisut', 'modularity'),
                        'kn' => __('Kannada', 'modularity'),
                        'kr' => __('Kanuri', 'modularity'),
                        'ks' => __('Kashmiri', 'modularity'),
                        'kk' => __('Kazakh', 'modularity'),
                        'km' => __('Khmer', 'modularity'),
                        'ki' => __('Kikuyu, Gikuyu', 'modularity'),
                        'rw' => __('Kinyarwanda', 'modularity'),
                        'ky' => __('Kirghiz, Kyrgyz', 'modularity'),
                        'kv' => __('Komi', 'modularity'),
                        'kg' => __('Kongo', 'modularity'),
                        'ko' => __('Korean', 'modularity'),
                        'ku' => __('Kurdish', 'modularity'),
                        'kj' => __('Kwanyama, Kuanyama', 'modularity'),
                        'la' => __('Latin', 'modularity'),
                        'lb' => __('Luxembourgish', 'modularity'),
                        'lg' => __('Luganda', 'modularity'),
                        'li' => __('Limburgish', 'modularity'),
                        'ln' => __('Lingala', 'modularity'),
                        'lo' => __('Lao', 'modularity'),
                        'lt' => __('Lithuanian', 'modularity'),
                        'lu' => __('Luba-Katanga', 'modularity'),
                        'lv' => __('Latvian', 'modularity'),
                        'gv' => __('Manx', 'modularity'),
                        'mk' => __('Macedonian', 'modularity'),
                        'mg' => __('Malagasy', 'modularity'),
                        'ms' => __('Malay', 'modularity'),
                        'ml' => __('Malayalam', 'modularity'),
                        'mt' => __('Maltese', 'modularity'),
                        'mi' => __('Māori', 'modularity'),
                        'mr' => __('Marathi', 'modularity'),
                        'mh' => __('Marshallese', 'modularity'),
                        'mn' => __('Mongolian', 'modularity'),
                        'na' => __('Nauru', 'modularity'),
                        'nv' => __('Navajo', 'modularity'),
                        'nb' => __('Norwegian Bokmål', 'modularity'),
                        'nd' => __('North Ndebele', 'modularity'),
                        'ng' => __('Ndonga', 'modularity'),
                        'nn' => __('Norwegian Nynorsk', 'modularity'),
                        'no' => __('Norwegian', 'modularity'),
                        'ii' => __('Nuosu', 'modularity'),
                        'nr' => __('South Ndebele', 'modularity'),
                        'oc' => __('Occitan', 'modularity'),
                        'oj' => __('Ojibwe', 'modularity'),
                        'om' => __('Oromo', 'modularity'),
                        'or' => __('Oriya', 'modularity'),
                        'os' => __('Ossetian', 'modularity'),
                        'pa' => __('Panjabi', 'modularity'),
                        'pi' => __('Pāli', 'modularity'),
                        'fa' => __('Persian', 'modularity'),
                        'pl' => __('Polish', 'modularity'),
                        'ps' => __('Pashto', 'modularity'),
                        'pt' => __('Portuguese', 'modularity'),
                        'qu' => __('Quechua', 'modularity'),
                        'rm' => __('Romansh', 'modularity'),
                        'rn' => __('Kirundi', 'modularity'),
                        'ro' => __('Romanian', 'modularity'),
                        'ru' => __('Russian', 'modularity'),
                        'sa' => __('Sanskrit', 'modularity'),
                        'sc' => __('Sardinian', 'modularity'),
                        'sd' => __('Sindhi', 'modularity'),
                        'se' => __('Northern Sami', 'modularity'),
                        'sm' => __('Samoan', 'modularity'),
                        'sg' => __('Sango', 'modularity'),
                        'sr' => __('Serbian', 'modularity'),
                        'gd' => __('Scottish Gaelic', 'modularity'),
                        'sn' => __('Shona', 'modularity'),
                        'si' => __('Sinhala', 'modularity'),
                        'sk' => __('Slovak', 'modularity'),
                        'sl' => __('Slovene', 'modularity'),
                        'so' => __('Somali', 'modularity'),
                        'st' => __('Southern Sotho', 'modularity'),
                        'es' => __('Spanish', 'modularity'),
                        'su' => __('Sundanese', 'modularity'),
                        'sw' => __('Swahili', 'modularity'),
                        'ss' => __('Swati', 'modularity'),
                        'sv' => __('Swedish', 'modularity'),
                        'ta' => __('Tamil', 'modularity'),
                        'te' => __('Telugu', 'modularity'),
                        'tg' => __('Tajik', 'modularity'),
                        'th' => __('Thai', 'modularity'),
                        'ti' => __('Tigrinya', 'modularity'),
                        'bo' => __('Tibetan', 'modularity'),
                        'tk' => __('Turkmen', 'modularity'),
                        'tl' => __('Tagalog', 'modularity'),
                        'tn' => __('Tswana', 'modularity'),
                        'to' => __('Tonga', 'modularity'),
                        'tr' => __('Turkish', 'modularity'),
                        'ts' => __('Tsonga', 'modularity'),
                        'tt' => __('Tatar', 'modularity'),
                        'tw' => __('Twi', 'modularity'),
                        'ty' => __('Tahitian', 'modularity'),
                        'ug' => __('Uighur, Uyghur', 'modularity'),
                        'uk' => __('Ukrainian', 'modularity'),
                        'ur' => __('Urdu', 'modularity'),
                        'uz' => __('Uzbek', 'modularity'),
                        've' => __('Venda', 'modularity'),
                        'vi' => __('Vietnamese', 'modularity'),
                        'vo' => __('Volapük', 'modularity'),
                        'wa' => __('Walloon', 'modularity'),
                        'cy' => __('Welsh', 'modularity'),
                        'wo' => __('Wolof', 'modularity'),
                        'fy' => __('Western Frisian', 'modularity'),
                        'xh' => __('Xhosa', 'modularity'),
                        'yi' => __('Yiddish', 'modularity'),
                        'yo' => __('Yoruba', 'modularity'),
                        'za' => __('Zhuang', 'modularity'),
                    ),
                    'default_value' => __('sv', 'modularity'),
                    'return_format' => 'array',
                    'multiple' => 0,
                    'allow_null' => 0,
                    'ui' => 0,
                    'ajax' => 0,
                    'placeholder' => '',
                    'parent_repeater' => 'field_637f27e8eb86c',
                ),
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-video',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/video',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => '',
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));
}