<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5756ce3e48783',
    'title' => 'Files',
    'fields' => array(
        0 => array(
            'sub_fields' => array(
                0 => array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_57fb42b2cb415',
                    'label' => __('Key', 'modularity'),
                    'name' => 'key',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '20',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                1 => array(
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'key' => 'field_57fb42bacb416',
                    'label' => __('Titel', 'modularity'),
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => __('Add column', 'modularity'),
            'collapsed' => '',
            'key' => 'field_57fb42a3cb414',
            'label' => __('Columns', 'modularity'),
            'name' => 'columns',
            'type' => 'repeater',
            'instructions' => __('The key should be used in each file\'s column value as reference.', 'modularity'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        1 => array(
            'sub_fields' => array(
                0 => array(
                    'return_format' => 'array',
                    'library' => 'all',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                    'key' => 'field_57fb4218cb40f',
                    'label' => __('File', 'modularity'),
                    'name' => 'file',
                    'type' => 'file',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                1 => array(
                    'sub_fields' => array(
                        0 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_57fb4266cb411',
                            'label' => __('Column key', 'modularity'),
                            'name' => 'key',
                            'type' => 'text',
                            'instructions' => __('Key reference from the column field', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '20',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                        1 => array(
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'key' => 'field_57fb427fcb412',
                            'label' => __('Value', 'modularity'),
                            'name' => 'value',
                            'type' => 'text',
                            'instructions' => __('The value for this column', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                        ),
                    ),
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => __('Add column', 'modularity'),
                    'collapsed' => '',
                    'key' => 'field_57fb423bcb410',
                    'label' => __('Fields', 'modularity'),
                    'name' => 'fields',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                ),
            ),
            'min' => 1,
            'max' => 0,
            'layout' => 'block',
            'button_label' => __('Add file', 'modularity'),
            'collapsed' => '',
            'key' => 'field_57fb41f2cb40e',
            'label' => __('Files', 'modularity'),
            'name' => 'file_list',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
        2 => array(
            'default_value' => 1,
            'message' => __('Allow filtering', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
            'key' => 'field_587600817ff7f',
            'label' => __('Filter', 'modularity'),
            'name' => 'show_filter',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-fileslist',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
    'modified' => 1484128422,
    'local' => 'json',
));
}