<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_5666a2a71d806',
    'title' => 'Table Editor',
    'fields' => array(
        0 => array(
            'key' => 'field_5731982808842',
            'label' => __('Datatyp', 'modularity'),
            'name' => 'mod_table_data_type',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'horizontal',
            'choices' => array(
                'manual' => __('Manuell inmatning', 'modularity'),
                'csv' => __('Importera CSV', 'modularity'),
            ),
            'default_value' => '',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        1 => array(
            'key' => 'field_57319c3b08843',
            'label' => __('CSV-fil', 'modularity'),
            'name' => 'mod_table_csv_file',
            'type' => 'file',
            'instructions' => __('CSV-formatterad fil', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731982808842',
                        'operator' => '==',
                        'value' => 'csv',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '.csv',
        ),
        2 => array(
            'key' => 'field_5731a138b52aa',
            'label' => __('CSV-avgränsare', 'modularity'),
            'name' => 'mod_table_csv_delimiter',
            'type' => 'text',
            'instructions' => __('Tecken som används i CSV-filen som avgränsare. Brukar vara kommatecken eller semikolon.', 'modularity'),
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731982808842',
                        'operator' => '==',
                        'value' => 'csv',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => ';',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        3 => array(
            'key' => 'field_57e8db8cf1ece',
            'label' => __('Storlek', 'modularity'),
            'name' => 'mod_table_size',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'horizontal',
            'choices' => array(
                'table-sm' => __('Liten', 'modularity'),
                'table-md' => __('Medium (standard)', 'modularity'),
                'table-lg' => __('Stor', 'modularity'),
            ),
            'default_value' => 'table-md',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        4 => array(
            'key' => 'field_5666a3e0d2d29',
            'label' => __('Sidbläddring', 'modularity'),
            'name' => 'mod_table_pagination',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Ja, använd sidbläddning för tabellen', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_5666a59673385',
            'label' => __('Antal inlägg/sidor', 'modularity'),
            'name' => 'mod_table_pagination_count',
            'type' => 'number',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5666a3e0d2d29',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => 10,
            'min' => 1,
            'max' => 500,
            'step' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        6 => array(
            'key' => 'field_5666a459d2d2a',
            'label' => __('Aktivera sök', 'modularity'),
            'name' => 'mod_table_search',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Ja, aktivera sök i denna tabell', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        7 => array(
            'key' => 'field_5666a63a48379',
            'label' => __('Sökfras', 'modularity'),
            'name' => 'mod_table_search_query',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5666a459d2d2a',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 50,
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'Search in list',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
        8 => array(
            'key' => 'field_56e181adef7ac',
            'label' => __('Aktivera kolumnsortering', 'modularity'),
            'name' => 'mod_table_ordering',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Ja, aktivera sortering', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-table',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}