<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_56a5e99108991',
    'title' => __('Slider', 'modularity'),
    'fields' => array(
        0 => array(
            'key' => 'field_573dce058a66t',
            'label' => __('Slider layout', 'modularity'),
            'name' => 'slider_layout',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'default' => __('Default', 'modularity'),
                'circle' => __('Circle slides', 'modularity'),
            ),
            'default_value' => array(
                0 => __('default', 'modularity'),
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        1 => array(
            'key' => 'field_573dce058a66e',
            'label' => __('Slider format', 'modularity'),
            'name' => 'slider_format',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'ratio-36-7' => __('Wide (36:7)', 'modularity'),
                'ratio-10-3' => __('Wide (10:3)', 'modularity'),
                'ratio-16-9' => __('Normal (16:9, video)', 'modularity'),
                'ratio-4-3' => __('Square (4:3)', 'modularity'),
            ),
            'default_value' => array(
                0 => __('ratio-16-9', 'modularity'),
            ),
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_58934110b566f',
            'label' => __('Slide columns', 'modularity'),
            'name' => 'slide_columns',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'multiple' => 0,
            'allow_null' => 0,
            'choices' => array(
                1 => __('1', 'modularity'),
                2 => __('2', 'modularity'),
                3 => __('3', 'modularity'),
                4 => __('4', 'modularity'),
                5 => __('5', 'modularity'),
            ),
            'default_value' => array(
                0 => 1,
            ),
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
            'return_format' => 'value',
        ),
        3 => array(
            'key' => 'field_58934110b566e',
            'label' => __('Slide alignment', 'modularity'),
            'name' => 'slide_align',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'left' => __('Vänster', 'modularity'),
                'center' => __('Centrerad', 'modularity'),
                'right' => __('Höger', 'modularity'),
            ),
            'default_value' => array(
                0 => __('center', 'modularity'),
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        4 => array(
            'key' => 'field_58cfe67cb211b',
            'label' => __('Slider height', 'modularity'),
            'name' => 'slider_height',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_573dce058a66e',
                        'operator' => '==',
                        'value' => 'ratio-10-3',
                    ),
                ),
                1 => array(
                    0 => array(
                        'field' => 'field_573dce058a66e',
                        'operator' => '==',
                        'value' => 'ratio-36-7',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 1,
            'message' => __('Force slider to recomended minimum/maximum height', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        5 => array(
            'key' => 'field_56a5e994398d6',
            'label' => __('Slides', 'modularity'),
            'name' => 'slides',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                0 => array(
                    'key' => '56a5ed29398db',
                    'name' => 'image',
                    'label' => __('Image', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_56a5ed2f398dc',
                            'label' => 'Desktop image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => 'This image will be used in larger screens. Preferably a widescreen image.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        1 => array(
                            'key' => 'field_570f4e9b10c26',
                            'label' => 'Mobile image',
                            'name' => 'mobile_image',
                            'type' => 'image',
                            'instructions' => 'This image will be used in smaller screens. Preferably a square image.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        2 => array(
                            'key' => 'field_56ab224ac2c28',
                            'label' => 'Text overlay',
                            'name' => 'activate_textblock',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Enable text overlay on this slide',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        3 => array(
                            'key' => 'field_56e7fa230ee09',
                            'label' => 'Text position',
                            'name' => 'textblock_position',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56ab224ac2c28',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'bottom' => 'Bottom banner',
                            ),
                            'default_value' => array(
                                0 => 'bottom',
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                        4 => array(
                            'key' => 'field_5702597b7d869',
                            'label' => 'Titel',
                            'name' => 'textblock_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56e7fa230ee09',
                                        'operator' => '==',
                                        'value' => 'center',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        5 => array(
                            'key' => 'field_56ab235393f04',
                            'label' => 'Innehåll',
                            'name' => 'textblock_content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56ab224ac2c28',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => 250,
                            'rows' => 2,
                            'new_lines' => 'br',
                        ),
                        6 => array(
                            'key' => 'field_56fa82a2d464d',
                            'label' => 'Link',
                            'name' => 'link_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'false' => 'No link',
                                'internal' => 'Internal',
                                'external' => 'External',
                            ),
                            'default_value' => 'false',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        7 => array(
                            'key' => 'field_56fa8313d4650',
                            'label' => 'Url',
                            'name' => 'link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        8 => array(
                            'key' => 'field_56fa8331d4651',
                            'label' => 'Sida',
                            'name' => 'link_url',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'allow_archives' => 1,
                        ),
                        9 => array(
                            'key' => 'field_56fa82dcd464e',
                            'label' => 'New window',
                            'name' => 'link_target',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Yes, open link in new window',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                1 => array(
                    'key' => '56a5e9a5bbaf1',
                    'name' => 'video',
                    'label' => __('Video', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_56a5eada398d7',
                            'label' => 'Typ',
                            'name' => 'type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'upload' => 'Upload video',
                                'embed' => 'Embed (YouTube or Vimeo link)',
                            ),
                            'default_value' => '',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        1 => array(
                            'key' => 'field_56a5eb09398d8',
                            'label' => 'Video: mp4',
                            'name' => 'video_mp4',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33,333',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'mp4',
                        ),
                        2 => array(
                            'key' => 'field_56b9e2102128f',
                            'label' => 'Video: webm',
                            'name' => 'video_webm',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33,333',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'webm',
                        ),
                        3 => array(
                            'key' => 'field_56b9e26c21290',
                            'label' => 'Video: ogg',
                            'name' => 'video_ogg',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33,333',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'ogg',
                        ),
                        4 => array(
                            'key' => 'field_56a5ed47398dd',
                            'label' => 'Embed link',
                            'name' => 'embed_link',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'embed',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        5 => array(
                            'key' => 'field_56b9e2a221291',
                            'label' => 'Placeholder Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => 1140,
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg',
                        ),
                        6 => array(
                            'key' => 'field_56b9f3dba4f22',
                            'label' => 'Text overlay',
                            'name' => 'activate_textblock',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Enable text overlay on this slide',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        7 => array(
                            'key' => 'field_56b9f3b8d7720',
                            'label' => 'Innehåll',
                            'name' => 'textblock_content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56b9f3dba4f22',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                    1 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'new_lines' => 'br',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        8 => array(
                            'key' => 'field_56e7fa620ee0a',
                            'label' => 'Text position',
                            'name' => 'textblock_position',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56b9f3dba4f22',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                    1 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'multiple' => 0,
                            'allow_null' => 0,
                            'choices' => array(
                                'bottom' => 'Bottom banner',
                                'center' => 'Centered',
                            ),
                            'default_value' => array(
                                0 => 'bottom',
                            ),
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                            'disabled' => 0,
                            'readonly' => 0,
                        ),
                        9 => array(
                            'key' => 'field_56fa87ec3ace2',
                            'label' => 'Link',
                            'name' => 'link_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'false' => 'No link',
                                'internal' => 'Internal',
                                'external' => 'External',
                            ),
                            'default_value' => 'false',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        10 => array(
                            'key' => 'field_56fa87fa3ace4',
                            'label' => 'Url',
                            'name' => 'link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                    1 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        11 => array(
                            'key' => 'field_56fa88043ace5',
                            'label' => 'Sida',
                            'name' => 'link_url',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                    1 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'allow_archives' => 1,
                        ),
                        12 => array(
                            'key' => 'field_56fa880c3ace6',
                            'label' => 'New window',
                            'name' => 'link_target',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                    1 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => 'Yes, open link in new window',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                2 => array(
                    'key' => '573d5aca26b8e',
                    'name' => 'featured',
                    'label' => __('Featured content', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_573d5ae726b8f',
                            'label' => 'Desktop Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => 'This image will be used in larger screens.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 51,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        1 => array(
                            'key' => 'field_573d5b5826b90',
                            'label' => 'Mobile Image',
                            'name' => 'mobile_image',
                            'type' => 'image',
                            'instructions' => 'This image will be used in smaller screens.',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 49,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        2 => array(
                            'key' => 'field_573d5c0508765',
                            'label' => 'Link',
                            'name' => 'link_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 51,
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'false' => 'No link',
                                'internal' => 'Internal',
                                'external' => 'External',
                            ),
                            'default_value' => 'false',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        3 => array(
                            'key' => 'field_573d5c5c08766',
                            'label' => 'Sida',
                            'name' => 'link_url',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                    1 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => 39,
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'allow_archives' => 1,
                        ),
                        4 => array(
                            'key' => 'field_573d5c6808768',
                            'label' => 'Url',
                            'name' => 'link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                    1 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => 39,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        5 => array(
                            'key' => 'field_573d5e48efd93',
                            'label' => 'New window',
                            'name' => 'link_target',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => 10,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => '',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        6 => array(
                            'key' => 'field_573d600eb104f',
                            'label' => 'Titel',
                            'name' => 'textblock_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => 'Ange din titel här',
                            'prepend' => '',
                            'append' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        7 => array(
                            'key' => 'field_573d604fb1050',
                            'label' => 'Innehåll',
                            'name' => 'textblock_content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'new_lines' => 'br',
                            'maxlength' => 250,
                            'placeholder' => '',
                            'rows' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'min' => 1,
            'max' => '',
            'button_label' => __('Add slide', 'modularity'),
        ),
        6 => array(
            'key' => 'field_5731c6d886811',
            'label' => __('Autoslide', 'modularity'),
            'name' => 'slides_autoslide',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 51,
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Automatically slide between slides', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        7 => array(
            'key' => 'field_5731c78886813',
            'label' => __('Slide timeout', 'modularity'),
            'name' => 'slides_slide_timeout',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731c6d886811',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 49,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'min' => 1,
            'max' => 20,
            'step' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('seconds', 'modularity'),
            'readonly' => 0,
            'disabled' => 0,
        ),
        8 => array(
            'key' => 'field_573d8880abc96',
            'label' => __('Navigation position', 'modularity'),
            'name' => 'navigation_position',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 51,
                'class' => '',
                'id' => '',
            ),
            'layout' => 'horizontal',
            'choices' => array(
                'center' => __('Centrerad', 'modularity'),
                'bottom' => __('Bottom', 'modularity'),
            ),
            'default_value' => __('center', 'modularity'),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        9 => array(
            'key' => 'field_573d88e2abc97',
            'label' => __('Show navigation', 'modularity'),
            'name' => 'show_navigation',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 49,
                'class' => '',
                'id' => '',
            ),
            'layout' => 'horizontal',
            'choices' => array(
                'always' => __('Always visible', 'modularity'),
                'hover' => __('Only on hover', 'modularity'),
            ),
            'default_value' => '',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        10 => array(
            'key' => 'field_58933fb6f5ed4',
            'label' => __('Additional options', 'modularity'),
            'name' => 'additional_options',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'horizontal',
            'choices' => array(
                'wrapAround' => __('Continues scroll (no ending slide)', 'modularity'),
                'pageDots' => __('Pages dot navigation', 'modularity'),
                'freeScroll' => __('No scroll snapping', 'modularity'),
                'groupCells' => __('Group slides', 'modularity'),
            ),
            'default_value' => array(
                0 => __('wrapAround', 'modularity'),
                1 => __('pageDots', 'modularity'),
            ),
            'allow_custom' => 0,
            'save_custom' => 0,
            'toggle' => 0,
            'return_format' => 'value',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-slider',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
));
}