<?php 

if (function_exists('acf_add_local_field_group')) {
    acf_add_local_field_group(array(
    'key' => 'group_56a5e99108991',
    'title' => 'Slider',
    'fields' => array(
        0 => array(
            'key' => 'field_573dce058a66t',
            'label' => __('Sliderlayout', 'modularity'),
            'name' => 'slider_layout',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'default' => __('Standard', 'modularity'),
                'circle' => __('Cirkulära slides', 'modularity'),
                'centerOverlay' => __('Center Overlay', 'modularity'),
            ),
            'default_value' => 'default',
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        1 => array(
            'key' => 'field_573dce058a66e',
            'label' => __('Sliderformat', 'modularity'),
            'name' => 'slider_format',
            'type' => 'select',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'ratio-36-7' => __('Bred (36:7)', 'modularity'),
                'ratio-10-3' => __('Bred (10:3)', 'modularity'),
                'ratio-16-9' => __('Normal (16:9, video)', 'modularity'),
                'ratio-4-3' => __('Kvadrat (4:3)', 'modularity'),
            ),
            'default_value' => 'ratio-16-9',
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        2 => array(
            'key' => 'field_56a5e994398d6',
            'label' => __('Slides', 'modularity'),
            'name' => 'slides',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                0 => array(
                    'key' => '56a5ed29398db',
                    'name' => 'image',
                    'label' => __('Bild', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_56a5ed2f398dc',
                            'label' => __('Desktop image', 'modularity'),
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => __('This image will be used in larger screens. Preferably a widescreen image.', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        1 => array(
                            'key' => 'field_570f4e9b10c26',
                            'label' => __('Mobile image', 'modularity'),
                            'name' => 'mobile_image',
                            'type' => 'image',
                            'instructions' => __('This image will be used in smaller screens. Preferably a square image.', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 50,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        2 => array(
                            'key' => 'field_56e7fa230ee09',
                            'label' => __('Text position', 'modularity'),
                            'name' => 'textblock_position',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56ab224ac2c28',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'multiple' => 0,
                            'allow_null' => 0,
                            'choices' => array(
                                'bottom' => __('Bottom banner', 'modularity'),
                                'center' => __('Centered', 'modularity'),
                            ),
                            'default_value' => 'bottom',
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                            'disabled' => 0,
                            'readonly' => 0,
                        ),
                        3 => array(
                            'key' => 'field_5702597b7d869',
                            'label' => __('Titel', 'modularity'),
                            'name' => 'textblock_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56e7fa230ee09',
                                        'operator' => '==',
                                        'value' => 'center',
                                    ),
                                ),
                                1 => array(
                                    0 => array(
                                        'field' => 'field_56e7fa230ee09',
                                        'operator' => '==',
                                        'value' => 'bottom',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        4 => array(
                            'key' => 'field_56ab235393f04',
                            'label' => __('Innehåll', 'modularity'),
                            'name' => 'textblock_content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56ab224ac2c28',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'new_lines' => 'br',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        5 => array(
                            'key' => 'field_56fa82a2d464d',
                            'label' => __('Länk', 'modularity'),
                            'name' => 'link_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'false' => __('No link', 'modularity'),
                                'internal' => __('Intern', 'modularity'),
                                'external' => __('Extern', 'modularity'),
                            ),
                            'default_value' => 'false',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        6 => array(
                            'key' => 'field_56fa8313d4650',
                            'label' => __('Url', 'modularity'),
                            'name' => 'link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        7 => array(
                            'key' => 'field_56fa8331d4651',
                            'label' => __('Sida', 'modularity'),
                            'name' => 'link_url',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'allow_archives' => 1,
                        ),
                        8 => array(
                            'key' => 'field_56fa82dcd464e',
                            'label' => __('New window', 'modularity'),
                            'name' => 'link_target',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56fa82a2d464d',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Yes, open link in new window', 'modularity'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                1 => array(
                    'key' => '56a5e9a5bbaf1',
                    'name' => 'video',
                    'label' => __('Video', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_56a5eada398d7',
                            'label' => __('Typ', 'modularity'),
                            'name' => 'type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'upload' => __('Ladda upp video', 'modularity'),
                                'embed' => __('Bädda in (YouTube eller Vimeo-länk)', 'modularity'),
                            ),
                            'default_value' => '',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        1 => array(
                            'key' => 'field_56a5eb09398d8',
                            'label' => __('Video: mp4', 'modularity'),
                            'name' => 'video_mp4',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33,333',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'mp4',
                        ),
                        2 => array(
                            'key' => 'field_56b9e2102128f',
                            'label' => __('Video: webm', 'modularity'),
                            'name' => 'video_webm',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33,333',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'webm',
                        ),
                        3 => array(
                            'key' => 'field_56b9e26c21290',
                            'label' => __('Video: ogg', 'modularity'),
                            'name' => 'video_ogg',
                            'type' => 'file',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33,333',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'library' => 'all',
                            'min_size' => '',
                            'max_size' => 20,
                            'mime_types' => 'ogg',
                        ),
                        4 => array(
                            'key' => 'field_5aaa6576ed65f',
                            'label' => __('Show pause Icon', 'modularity'),
                            'name' => 'show_pause_icon',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => __('Show pause icon', 'modularity'),
                            'default_value' => 1,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        5 => array(
                            'key' => 'field_5aaa66deed660',
                            'label' => __('Pause icon transparency', 'modularity'),
                            'name' => 'pause_icon_transparacy',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5aaa6576ed65f',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                1 => __('100%', 'modularity'),
                                9 => __('90%', 'modularity'),
                                8 => __('80%', 'modularity'),
                                7 => __('70%', 'modularity'),
                                6 => __('60%', 'modularity'),
                                5 => __('50%', 'modularity'),
                                4 => __('40%', 'modularity'),
                                3 => __('30%', 'modularity'),
                                2 => __('20%', 'modularity'),
                            ),
                            'default_value' => '60%',
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'ajax' => 0,
                            'return_format' => 'value',
                            'placeholder' => '',
                        ),
                        6 => array(
                            'key' => 'field_5aaa6e50f06ba',
                            'label' => __('Show pause icon on hover', 'modularity'),
                            'name' => 'show_pause_icon_on_hover',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_5aaa6576ed65f',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '33',
                                'class' => '',
                                'id' => '',
                            ),
                            'message' => '',
                            'default_value' => 1,
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        7 => array(
                            'key' => 'field_56a5ed47398dd',
                            'label' => __('Inbäddningslänk', 'modularity'),
                            'name' => 'embed_link',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'embed',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        8 => array(
                            'key' => 'field_56b9e2a221291',
                            'label' => __('Placeholder Image', 'modularity'),
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => 1140,
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg',
                        ),
                        9 => array(
                            'key' => 'field_56b9f3dba4f22',
                            'label' => __('Text overlay', 'modularity'),
                            'name' => 'activate_textblock',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Enable text overlay on this slide', 'modularity'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        10 => array(
                            'key' => 'field_56b9f3b8d7720',
                            'label' => __('Innehåll', 'modularity'),
                            'name' => 'textblock_content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56b9f3dba4f22',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                    1 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'new_lines' => 'br',
                            'maxlength' => '',
                            'placeholder' => '',
                            'rows' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        11 => array(
                            'key' => 'field_56e7fa620ee0a',
                            'label' => __('Text position', 'modularity'),
                            'name' => 'textblock_position',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56b9f3dba4f22',
                                        'operator' => '==',
                                        'value' => '1',
                                    ),
                                    1 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'multiple' => 0,
                            'allow_null' => 0,
                            'choices' => array(
                                'bottom' => __('Bottom banner', 'modularity'),
                                'center' => __('Centered', 'modularity'),
                            ),
                            'default_value' => 'bottom',
                            'ui' => 0,
                            'ajax' => 0,
                            'placeholder' => '',
                            'return_format' => 'value',
                            'disabled' => 0,
                            'readonly' => 0,
                        ),
                        12 => array(
                            'key' => 'field_56fa87ec3ace2',
                            'label' => __('Länk', 'modularity'),
                            'name' => 'link_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'false' => __('No link', 'modularity'),
                                'internal' => __('Intern', 'modularity'),
                                'external' => __('Extern', 'modularity'),
                            ),
                            'default_value' => 'false',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        13 => array(
                            'key' => 'field_56fa87fa3ace4',
                            'label' => __('Url', 'modularity'),
                            'name' => 'link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                    1 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        14 => array(
                            'key' => 'field_56fa88043ace5',
                            'label' => __('Sida', 'modularity'),
                            'name' => 'link_url',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                    1 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'allow_archives' => 1,
                        ),
                        15 => array(
                            'key' => 'field_56fa880c3ace6',
                            'label' => __('New window', 'modularity'),
                            'name' => 'link_target',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_56a5eada398d7',
                                        'operator' => '==',
                                        'value' => 'upload',
                                    ),
                                    1 => array(
                                        'field' => 'field_56fa87ec3ace2',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => __('Yes, open link in new window', 'modularity'),
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                2 => array(
                    'key' => '573d5aca26b8e',
                    'name' => 'featured',
                    'label' => __('Featured content', 'modularity'),
                    'display' => 'block',
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_573d5ae726b8f',
                            'label' => __('Desktop Image', 'modularity'),
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => __('This image will be used in larger screens.', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 51,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        1 => array(
                            'key' => 'field_573d5b5826b90',
                            'label' => __('Mobile Image', 'modularity'),
                            'name' => 'mobile_image',
                            'type' => 'image',
                            'instructions' => __('This image will be used in smaller screens.', 'modularity'),
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 49,
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => 'png,jpg,jpeg',
                        ),
                        2 => array(
                            'key' => 'field_573d5c0508765',
                            'label' => __('Länk', 'modularity'),
                            'name' => 'link_type',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => 51,
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'horizontal',
                            'choices' => array(
                                'false' => __('No link', 'modularity'),
                                'internal' => __('Intern', 'modularity'),
                                'external' => __('Extern', 'modularity'),
                            ),
                            'default_value' => 'false',
                            'other_choice' => 0,
                            'save_other_choice' => 0,
                            'allow_null' => 0,
                            'return_format' => 'value',
                        ),
                        3 => array(
                            'key' => 'field_573d5c5c08766',
                            'label' => __('Sida', 'modularity'),
                            'name' => 'link_url',
                            'type' => 'page_link',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                    1 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '==',
                                        'value' => 'internal',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => 39,
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                            ),
                            'taxonomy' => array(
                            ),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'allow_archives' => 1,
                        ),
                        4 => array(
                            'key' => 'field_573d5c6808768',
                            'label' => __('Url', 'modularity'),
                            'name' => 'link_url',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                    1 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '==',
                                        'value' => 'external',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => 39,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        5 => array(
                            'key' => 'field_573d5e48efd93',
                            'label' => __('New window', 'modularity'),
                            'name' => 'link_target',
                            'type' => 'true_false',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => array(
                                0 => array(
                                    0 => array(
                                        'field' => 'field_573d5c0508765',
                                        'operator' => '!=',
                                        'value' => 'false',
                                    ),
                                ),
                            ),
                            'wrapper' => array(
                                'width' => 10,
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => 0,
                            'message' => '',
                            'ui' => 0,
                            'ui_on_text' => '',
                            'ui_off_text' => '',
                        ),
                        6 => array(
                            'key' => 'field_573d600eb104f',
                            'label' => __('Titel', 'modularity'),
                            'name' => 'textblock_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => __('Ange din titel här', 'modularity'),
                            'prepend' => '',
                            'append' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                        7 => array(
                            'key' => 'field_573d604fb1050',
                            'label' => __('Innehåll', 'modularity'),
                            'name' => 'textblock_content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'new_lines' => 'br',
                            'maxlength' => 250,
                            'placeholder' => '',
                            'rows' => '',
                            'readonly' => 0,
                            'disabled' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'min' => 1,
            'max' => '',
            'button_label' => __('Add slide', 'modularity'),
        ),
        3 => array(
            'key' => 'field_5731c6d886811',
            'label' => __('Automatisk bläddring', 'modularity'),
            'name' => 'slides_autoslide',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 51,
                'class' => '',
                'id' => '',
            ),
            'default_value' => 0,
            'message' => __('Bläddra automatiskt mellan slides', 'modularity'),
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        4 => array(
            'key' => 'field_5731c78886813',
            'label' => __('Intervall för automatisk bläddring', 'modularity'),
            'name' => 'slides_slide_timeout',
            'type' => 'number',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_5731c6d886811',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => 49,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'min' => 1,
            'max' => 20,
            'step' => 1,
            'placeholder' => '',
            'prepend' => '',
            'append' => __('sekunder', 'modularity'),
            'readonly' => 0,
            'disabled' => 0,
        ),
        5 => array(
            'key' => 'field_573d8880abc96',
            'label' => __('Navigeringsposition', 'modularity'),
            'name' => 'navigation_position',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => 51,
                'class' => '',
                'id' => '',
            ),
            'layout' => 'horizontal',
            'choices' => array(
                'center' => __('Centrerad', 'modularity'),
                'bottom' => __('Botten', 'modularity'),
            ),
            'default_value' => 'center',
            'other_choice' => 0,
            'save_other_choice' => 0,
            'allow_null' => 0,
            'return_format' => 'value',
        ),
        6 => array(
            'key' => 'field_58933fb6f5ed4',
            'label' => __('Fler inställningar', 'modularity'),
            'name' => 'additional_options',
            'type' => 'checkbox',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'wrapAround' => __('Börja om efter sista sliden', 'modularity'),
            ),
            'allow_custom' => 0,
            'default_value' => array(
                0 => 'wrapAround',
            ),
            'layout' => 'horizontal',
            'toggle' => 0,
            'return_format' => 'value',
            'save_custom' => 0,
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-slider',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
}